# Generated by Django 4.1.5 on 2023-04-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
