# Generated by Django 4.1.5 on 2023-04-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
                ('delivery', models.CharField(max_length=100)),
                ('stars', models.FloatField()),
                ('picture', models.ImageField(default='products/default.jpg', upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('product_names', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Packed', 'Packed'), ('Loaded', 'Loaded'), ('Delivered', 'Delivered')], max_length=10)),
                ('tracking_num', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amazon_web.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_web.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_web.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
