# Generated by Django 4.1.5 on 2023-04-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
