# Generated by Django 4.1.5 on 2023-04-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0003_order_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
