# Generated by Django 4.1.5 on 2023-04-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0006_order_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('whid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=10)),
                ('y', models.IntegerField(default=10)),
            ],
        ),
    ]
