# Generated by Django 4.1.5 on 2023-04-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0008_remove_order_products_remove_order_quantities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='truck_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_web.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checked_out', 'checked_out'), ('requesting_inventory', 'requesting_inventory'), ('inventory_arrived', 'inventory_arrived'), ('packing', 'packing'), ('packed', 'packed'), ('booked_truck', 'booked_truck'), ('truck_arrived', 'truck_arrived'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='checked_out', max_length=50),
        ),
    ]
