# Generated by Django 4.1.5 on 2023-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0011_alter_order_whid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stars',
            field=models.FloatField(default=5.0),
        ),
    ]
