# Generated by Django 4.1.5 on 2023-04-23 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_web', '0002_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('tracking_num', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('products', models.JSONField(blank=True, default=dict)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('checked_out', 'checked_out'), ('requesting_inventory', 'requesting_inventory'), ('inventory_arrived', 'inventory_arrived'), ('packing', 'packing'), ('packed', 'packed'), ('booked_truck', 'booked_truck'), ('truck_arrive', 'truck_arrive'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='checked_out', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
