# Generated by Django 4.1.5 on 2023-04-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0004_alter_order_tracking_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='amazon_web.product'),
        ),
    ]
