# Generated by Django 4.1.5 on 2023-04-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0009_order_truck_id_order_whid_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='whid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazon_web.warehouse'),
        ),
    ]
