# Generated by Django 4.1.5 on 2023-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0010_alter_order_whid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='whid',
            field=models.IntegerField(default=1),
        ),
    ]
