# Generated by Django 4.1.5 on 2023-04-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0012_orderitem_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
