# Generated by Django 4.1.5 on 2023-04-27 16:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/wall.jpg', upload_to=users.models.profile_image_path),
        ),
    ]
